### ISSUE TITLE
Stylelint improvements for CSS modules

### ISSUE THREAD

**Issue by langermank** [primer/stylelint-config#387]
Just a list of some little improvements

- Default config to CSS first, treat SCSS as overrides 
- Support for CSS in JS (React)
- Upgrade stylelint to next major

**Rules**
- Better support for CSS variables
- Triage existing rules
- Better mapping for color CSS variables to properties 

### Tasks
- [ ] Rewite primer-borders
- [ ] Rewrite box-shadows
- [ ] Rewrite colors
- [ ] Delete no-deprecated-colors
- [ ] Add no deprecated variables
- [ ] Delete no-experimental variables
- [ ] Delete no-overrides
- [ ] Delete no-scale-colors
- [ ] Rewrite no-undefined-vars (research)
- [ ] Delete no-unused-vars
- [ ] Leave responsive-vars
- [ ] Rewrite primer-spacing
- [ ] Rewrite typography
- [ ] Rewrite utilities

**Comment by jonrohan** [comment]
Should be fixed in 13.1.0
